# POST a request to the lesson complete endpoint
POST http://localhost:8080/api/lesson/0/complete
Cookie: next-auth.session-token=;

###

# GET a request to the lesson complete endpoint
GET http://localhost:8080/api/lesson/0/complete